import {Validators} from '@angular/forms';

  export const UserColumns: any[] = [
    {accessor: 'FirstName', type: 'text', label: 'First Name'},
    {accessor: 'LastName', type: 'text', label: 'Last Name'},
    {accessor: 'Email', type: 'text', label: 'Email'},
    {accessor: 'UserAccessLevel', type: 'select', label: 'Access',  listAcc: 'Name'},
    {accessor: 'Status', type: 'checkbox', label: 'Status'},
    {accessor: 'Id', type: 'operation', label: 'Manage',  operation: ['edit', 'delete']},
  ];

  export const UserForms: any[] = [
    { id: 'Id',
      placeHolder: 'First Name',
      type: 'hidden',
      validator: ['0', Validators.required],
      class: 'form-control',
    },
    { id: 'FirstName',
      placeHolder: 'First Name',
      type: 'text',
      validator: ['', Validators.required],
      class: 'form-control',
    },
    { id: 'LastName',
      placeHolder: 'Last Name',
      type: 'text',
      validator: ['', Validators.required],
      class: 'form-control',
    },
    { id: 'Email',
      placeHolder: 'Email',
      type: 'text',
      validator: ['', Validators.email],
      class: 'form-control',
    },
    { id: 'Token',
      placeHolder: 'token',
      type: 'hidden',
      validator: ['g', Validators.required],
      class: 'form-control',
    },
    { id: 'Password',
      placeHolder: 'password',
      type: 'hidden',
      validator: ['admin123', Validators.required],
      class: 'form-control',
    },
    { id: 'Status',
      placeHolder: 'Active',
      type: 'hidden',
      validator: ['N', Validators.required],
      class: 'form-control',
    },
    { id: 'InsertedId',
      placeHolder: 'Active',
      type: 'hidden',
      validator: ['1', Validators.required],
      class: 'form-control',
    },
    { id: 'AccessLevel',
      placeHolder: 'Role',
      type: 'select',
      selectList: ['UserAccessLevels', 'Id', 'Name'],
      list: [],
      validator: ['', Validators.required],
      class: 'form-control',
    },
  ];


