import {Validators} from '@angular/forms';

export const UserForms: any[] = [
  { id: 'FirstName',
    placeHolder: 'First Name',
    type: 'text',
    validator: ['', Validators.required],
    class: 'form-control',
  },
  { id: 'LastName',
    placeHolder: 'Last Name',
    type: 'text',
    validator: ['', Validators.required],
    class: 'form-control',
  },
  { id: 'Email',
    placeHolder: 'Email',
    type: 'text',
    validator: ['', Validators.email],
    class: 'form-control',
  },
  { id: 'Token',
    placeHolder: 'token',
    type: 'hidden',
    validator: ['g', Validators.required],
    class: 'form-control',
  },
  { id: 'Password',
    placeHolder: 'password',
    type: 'hidden',
    validator: ['admin123', Validators.required],
    class: 'form-control',
  },
  { id: 'Status',
    placeHolder: 'Active',
    type: 'hidden',
    validator: ['N', Validators.required],
    class: 'form-control',
  },
  { id: 'InsertedId',
    placeHolder: 'Active',
    type: 'hidden',
    validator: ['1', Validators.required],
    class: 'form-control',
  },
  { id: 'AccessLevel',
    placeHolder: 'Role',
    type: 'select',
    list: [],
    validator: ['', Validators.required],
    class: 'form-control',
  },
];
